model_config:
  uniter:
    mask_probability: 0.15
    tasks:
      - mlm
      - itm
      - mrc
      - mrfr
      - wra
    heads:
      mlm:
        type: mlm
      itm:
        type: itm
      mrc:
        type: mrc
      mrfr:
        type: mrfr
      wra:
        type: wra

dataset_config:
  vqa2:
    return_features_info: true
    use_features: true
    use_images: false
    processors:
      text_processor:
        type: uniter_text_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0.15
          max_seq_length: 25

optimizer:
  type: adam_w
  params:
    lr: 5e-5
    eps: 1e-8

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 6000
    num_training_steps: 60000

evaluation:
  metrics:
  - vqa_accuracy

training:
  batch_size: 480
  lr_scheduler: true
  # Don't forget to update schedule_attributes if you update this
  max_updates: 60000
  early_stop:
    criteria: vqa2/vqa_accuracy
    minimize: false
